language: rust
dist: focal

before_install:
  - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -

matrix:
  include:
    - os: linux
      dist: focal
      rust: nightly

script:
  - rustup component add llvm-tools-preview
  - export RUSTFLAGS="-Zinstrument-coverage"
  - cargo build --verbose
  - LLVM_PROFILE_FILE="your_name-%p-%m.profraw" cargo test --verbose
  - ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
  - bash <(curl -s https://codecov.io/bash) -f lcov.info
